<?php

/**
 * AUTO-GENERATED by `mini aspects` — DO NOT EDIT.
 *
 * This file is regenerated on every `mini aspects` run. To add custom
 * bootstrap code for this aspect (register services, container bindings,
 * middleware, etc.), create a sibling `bootstrap.php` (no underscore).
 * It will be required automatically after the resource paths are added.
 */

\mini\Mini::$mini->paths->routes->addPath(__DIR__ . '/_routes');
\mini\Mini::$mini->paths->views->addPath(__DIR__ . '/_views');

if (is_file(__DIR__ . '/bootstrap.php')) {
    require __DIR__ . '/bootstrap.php';
}
